slam_toolbox:
  ros__parameters:

    # Frame configuration
    map_frame: map
    odom_frame: odom
    base_frame: base_link   # or "base_link" depending on your URDF
    scan_topic: /scan
    use_sim_time: true

    max_laser_range: 3.5  # meters

    # Core behavior
    mode: mapping   # options: "mapping", "localization", "mapping_continuous"
    slam_approach: "full"   # use the global-backend graph
    # tf_buffer_duration: 10.0  # seconds, for example

    resolution: 0.05
    map_update_interval: 1.0

    # General solver settings
    solver_plugin: "solver_plugins::CeresSolver"
    ceres_solver_options:
      max_num_iterations: 10
      num_threads: 4
